
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTMASTER_H
#define TESTMASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestMaster_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestMaster_Data;
extern UNS32 MasterMap1;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS32 MasterMap2;		/* Mapped at index 0x2001, subindex 0x00*/

#endif // TESTMASTER_H
